### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by dashcraft** [meganetaaan/docker-moddable-esp32#1]
I'm interested in how this dockerfile is used. Do we pull it and work from within the container?

**Comment by meganetaaan** [comment]
Yes you can! The pre-built image is available on [DockerHub](https://hub.docker.com/r/meganetaaan/moddable-esp32).

```sh
docker run -it --rm meganetaaan/moddable-esp32:latest /bin/bash
```

The latest ESP-IDF(v4.4) and moddable built on top of `public` branch are all set up.
You can call `mcconfig`, `mcrun` and other moddable commands withing the container.

**Comment by dashcraft** [comment]
Excellent! Thank you!
